### ISSUE TITLE
【开发任务】实现密码加盐哈希存储

### ISSUE THREAD

**Issue by joymufeng** [playcommunity/play-community#20]
## 1. 任务目的
加强用户密码保护措施，防止密码泄露。

## 2. 任务内容
使用Argon2算法重构现有的MD5摘要算法。Argon2是目前公认的最安全的密码哈希算法。

### 3.1 为models.User新增两个属性：
```
@Entity("common-user")
case class User(
...
salt: Option[String],
argon2Hash: Option[String]
)
```
- `salt`存放16字节盐值，每个用户盐值单独生成，生成方法如下：
```
byte[] salt = new byte[16];
SecureRandom r = new SecureRandom();
r.nextBytes(salt);
```
- `argon2Hash`存放Argon2密码摘要。

### 3.2 在`security`包下新增`PasswordEncoder`接口和`Argon2PasswordEncoder`实现
- 实现时请参考：[Argon2PasswordEncoder.java](https://github.com/ckatzorke/spring-security-password-encoder-argon2/blob/master/src/main/java/de/ckatzorke/spring/security/password/encoder/Argon2PasswordEncoder.java)。
- 使用时直接注入`Argon2PasswordEncoder`实例。

### 3.3 重构登录模块
1） MD5 转 Argon2 时序图
如果用户尚未完成Argon2升级，则执行如下升级流程：
![argon2](https://user-images.githubusercontent.com/2126539/65861752-6c6e8b80-e39f-11e9-9675-6ac01ae47bc7.png)

2） 重构后登陆流程
在登录逻辑中增加MD5和Argon2的判断，分别执行不同的密码校验策略：
![argon2流程图](https://user-images.githubusercontent.com/2126539/65862913-c2443300-e3a1-11e9-9140-8b63d9411fcf.png)

### 3.4 重构关联模块
以下几个模块的重构逻辑与登录模块相同：
- 用户注册
- 用户密码更改
- 用户密码重置

**Comment by jxnu-liguobin** [comment]
我的理解是：增加新加密方式并兼容旧的方式，若使用旧的登录成功自动升级到新的，下次使用新的。是这样吗？若使用新的，说明已经升级过了

**Comment by jxnu-liguobin** [comment]
我的理解是：增加新加密方式并兼容旧的方式，若使用旧的登录成功自动升级到新的，下次使用新的。是这样吗？若使用新的，说明已经升级过了

**Comment by jxnu-liguobin** [comment]
m

**Comment by joymufeng** [comment]
> 我的理解是：增加新加密方式并兼容旧的方式，若使用旧的登录成功自动升级到新的，下次使用新的。是这样吗？若使用新的，说明已经升级过了

嗯嗯，对的

**Comment by joymufeng** [comment]
Argon2会自动生成盐值，后期考虑去掉salt。
