### ISSUE TITLE
【开发任务】重构帖子的编辑、删除鉴权逻辑，新增版主权限

### ISSUE THREAD

**Issue by joymufeng** [playcommunity/play-community#47]
新增checkResourcePermission[A](_idField: String)

**Comment by jxnu-liguobin** [comment]
SESSION中用户的信息可以封装到ActionFilter [UserRequest]。然后直接request.user。
可以作为一个新的任务。action重构 @joymufeng 
类似
//用户校验
`  object AuthAction extends ActionBuilder[UserRequest] with ActionRefiner[Request, UserRequest] {
    private val accountService: AccountService = service
    override protected def refine[A](request: Request[A]): Future[Either[Result, UserRequest[A]]] = {
      getUserFromRequest(request).map {
        case Some((user, accountDto)) => Right(new UserRequest(accountDto, user, request))
        case None => Left()
      }
    }`
//角色权限校验
` def AuthRequestTransFormer = new ActionTransformer[ProjectRequest, AuthRequest] {
    override protected def transform[A](request: ProjectRequest[A]): Future[AuthRequest[A]] = {
        roleService.getUserRole(request.帖子id, request.userId).map { role =>
          new AuthRequest[A](role, request)
      }
    }
  }
def PermissionCheckAction(permission: String) = AuthRequestTransFormer andThen new ActionFilter[AuthRequest] {
    override protected def filter[A](request: AuthRequest[A]): Future[Option[Result]] = {
      if (request.role.isRoot || AuthConstants.AllAllowed == permission) {//permission是代表权限的权限常量
        Future.successful(None)
      } else {
        permissionService.roleBaseCheck(request.帖子id, request.userId, permission) map {
          case true => None
          case false => Option(Results.Forbidden(ErrorMsg("只有拥有相关权限的人员才能进行此操作")))
        }
      }
    }
  }
`

使用 :
AuthAction andThen PermissionCheckAction("权限")。async {
 implicit request  => request.userId
}

**Comment by jxnu-liguobin** [comment]
通用代码已经写了一个example，https://github.com/jxnu-liguobin/scala-examples/blob/master/app/action/ActionComponent.scala

**Comment by joymufeng** [comment]
Resolved in this [Commit](https://github.com/playcommunity/play-community/commit/f1ee8892a84a5cd92f3ff6e9513a9df4c737a73e).
