### ISSUE TITLE
分享功能题库功能产生最新说说跳转短暂显示

### ISSUE THREAD

**Issue by shizeying** [playcommunity/play-community#48]
### Bug出处:
![image](https://user-images.githubusercontent.com/38680988/70492557-c5953100-1b3f-11ea-820e-4795f1b8d4bb.png)
&emsp;在互相点击分享和题库的功能的时候
![image](https://user-images.githubusercontent.com/38680988/70492589-e3fb2c80-1b3f-11ea-8c8c-a7108333c746.png)
在最新说说会有短暂的切换跳转,可以点击尝试下,我点击多次,发现确实存在

**Comment by joymufeng** [comment]
> 在最新说说会有短暂的切换跳转,可以点击尝试下,我点击多次,发现确实存在    

切换跳转具体是什么意思？是指最新说说本来是空白，然后数据瞬间加载进来吗？

**Comment by shizeying** [comment]
就是点击分享或者题库功能，在最新说说的部分，每点击一次，数据会先置为空，后恢复：这个是我录制的bug出处
![bug](https://user-images.githubusercontent.com/38680988/70533189-82fd4400-1b93-11ea-9cf2-ac61dde90e8b.gif)

**Comment by joymufeng** [comment]
会影响体验吗？说说是通过Vue+Ajax动态加载的，所以会闪一下。

**Comment by shizeying** [comment]
体验应该不会

**Comment by joymufeng** [comment]
OK，先关掉了，感谢反馈
