### ISSUE TITLE
【BUG】发现 Scala 技术圈功能中展示的博客更新时间有问题

### ISSUE THREAD

**Issue by LangInteger** [playcommunity/play-community#49]
- [页面链接](https://scalacn.cool/leaders)

![image](https://user-images.githubusercontent.com/17768055/70878022-be1bcf00-1ffa-11ea-8e5a-d845cf5f4aba.png)

如上面这位，显示更新时间为 `2019-10-30`，实际为 `2019-12-05` 发布的 [Akka Streams [3]: Operator Composition](https://pragmaticscala.com/post/2019/12/akka-streams-composition/)

**Comment by joymufeng** [comment]
目前是解析[RSS](https://pragmaticscala.com/index.xml)的第1个item的发布时间，刚看了下，是因为RSS未包含最新文章导致的，已改成从首页解析。

**Comment by LangInteger** [comment]
Thx!
