### ISSUE TITLE
替换代码中的绝对路径为相对路径

### ISSUE THREAD

**Issue by OldPanda** [playcommunity/play-community#5]
目前源码中某些链接的 url 包含着 playscala.cn 的地址，这样如果在本地运行，且没有修改的话，就会直接跳转到该网站，比如说这一行 https://github.com/playcommunity/play-community/blob/master/app/views/main.scala.html#L64 ，用户点击登录或者注册就会跳到在线论坛，而不是本地，所以开这个 issue 建议能做些修改。

我注意到 playscala.cn 网站并没有全站 https ，所以似乎需要 https://secure.playscala.cn/ 这样一个地址来处理用户敏感信息，如密码。所以我觉得可以考虑全站 https ，然后把这些路径改成相对的。这样对新用户来说，不需要触及太多的代码，就可以在自己的机器上运行起整个网站。

**Comment by joymufeng** [comment]
@OldPanda 目前确实存在某些地方硬编码了绝对路径，后面会修复这些问题。
